env:
  browser: true
  es2020: true
extends: eslint:recommended
rules:
  # Disabled as the linter doesn't understand Closure Compiler style imports
  # ("goog.require") and Closure Library's global symbols.
  no-undef: off
  # Disabled as causes spurious errors on Closure Compiler typedefs and casts.
  no-unused-vars: off
  # Enforce 80-column limit, with some reasonable exceptions.
  max-len:
    - error
    - ignoreComments: true
      ignoreUrls: true
      ignorePattern: ^(goog\.require|goog\.provide)\(.*\);$
  block-scoped-var: error
  guard-for-in: error
  new-parens: error
  no-array-constructor: error
  no-confusing-arrow: error
  no-constant-binary-expression: error
  no-constructor-return: error
  no-duplicate-imports: error
  no-eq-null: error
  no-extend-native: error
  no-invalid-this: error
  no-lone-blocks: error
  no-multi-assign: error
  no-new-native-nonconstructor: error
  no-octal-escape: error
  no-promise-executor-return: error
  no-return-assign: error
  no-self-compare: error
  no-sequences: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-private-class-members: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  prefer-const: error
  prefer-promise-reject-errors: error
  semi-spacing: error
  semi-style: error
  semi: error
overrides:
  # Parse specific files as ES Modules (the standard parser would fail).
  - files:
      example_js_standalone_smart_card_client_library/src/es-module-exports.js
    parserOptions:
      sourceType: module
