env:
  browser: true
  es2020: true
extends: eslint:recommended
rules:
  # Disabled as the linter doesn't understand Closure Compiler style imports
  # ("goog.require") and Closure Library's global symbols.
  no-undef: off
  # Disabled as causes spurious errors on Closure Compiler typedefs and casts.
  no-unused-vars: off
  # Enforce 80-column limit, with some reasonable exceptions.
  max-len:
    - error
    - ignoreComments: true
      ignoreUrls: true
      ignorePattern: ^(goog\.require|goog\.provide)\(.*\);$
  new-parens: error
  no-constant-binary-expression: error
  no-constructor-return: error
  no-duplicate-imports: error
  no-new-native-nonconstructor: error
  no-promise-executor-return: error
  no-self-compare: error
  no-template-curly-in-string: error
  no-unmodified-loop-condition: error
  no-unreachable-loop: error
  no-unused-private-class-members: error
  prefer-const: error
  semi: error
  semi-spacing: error
  semi-style: error
overrides:
  # Parse specific files as ES Modules (the standard parser would fail).
  - files:
      example_js_standalone_smart_card_client_library/src/es-module-exports.js
    parserOptions:
      sourceType: module
