name: 'Install build dependencies'
inputs:
  toolchain:
    description: '"emscripten", "pnacl", "asan_testing" or "coverage"'
    required: true
runs:
  using: 'composite'
  steps:
  # Update the Apt cache, since the default state in Github Actions VM might be
  # stalled, causing 404 errors when trying to install packages later.
  - name: Apt update
    shell: bash
    run: sudo apt-get update

  - name: Install dependencies
    shell: bash
    run: >
      sudo apt-get install -y
      autoconf
      autoconf-archive
      flex
      libsystemd-dev
      libudev-dev
      pkg-config

  - name: Set up Python 3
    uses: actions/setup-python@v3.1.2
    with:
      python-version: 3.9
      cache: pip

  - name: Initialize env
    shell: bash
    run: env/initialize.sh -t ${{ inputs.toolchain }}

  # Building in the analysis modes requires LLVM/Clang, as well as 32-bit
  # cross-compile versions of standard C and C++ libraries (needed as we're
  # building code in 32-bit mode on the 64-bit host).
  - name: Install LLVM toolchain
    if: ${{ inputs.toolchain == 'asan_testing' || inputs.toolchain == 'coverage' }}
    shell: bash
    run: >
      sudo apt-get install -y
      build-essential
      llvm
      clang
      libc6-dev-i386
      libstdc++-${ANALYSIS_LIBSTDCPP_VERSION}-dev-i386-cross
