name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 2
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 2.7
    - run: pip2 install six
    
    - name: Setup Python 3
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.9

    - name: Initialize env
      run: env/initialize.sh
      
    - name: Build
      run: make
