name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.9
        cache: pip

    - name: Initialize env
      run: env/initialize.sh

    - name: Compile in WebAssembly mode
      run: >
        source env/activate &&
          TOOLCHAIN=emscripten make -j30

    - name: Test in WebAssembly mode
      run: >
        source env/activate &&
          TOOLCHAIN=emscripten make test

    - name: Compile in NaCl mode
      run: >
        source env/activate &&
          source env/python2_venv/bin/activate &&
          TOOLCHAIN=pnacl make
