name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Update the Apt cache, since the default state in Github Actions VM might
    # be stalled, causing 404 errors when trying to install packages later.
    - name: Apt update
      run: sudo apt-get update

    - name: Set up Python 3
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.9
        cache: pip

    # Building in the coverage mode requires LLVM and Clang, as well as 32-bit
    # cross-compile versions of standard C and C++ libraries (needed as we're
    # building code in 32-bit mode on the 64-bit host).
    - name: Install coverage toolchain
      run: >
        sudo apt-get install -y
        build-essential
        llvm
        clang
        libc6-dev-i386
        libstdc++-10-dev-i386-cross

    - name: Initialize env
      run: env/initialize.sh

    - name: Compile in WebAssembly mode
      run: >
        source env/activate &&
          TOOLCHAIN=emscripten make -j30
    - name: Compile in NaCl mode
      run: >
        source env/activate &&
          source env/python2_venv/bin/activate &&
          TOOLCHAIN=pnacl make
